CREATE TABLE IF NOT EXISTS nifty50_stocks (
            symbol TEXT,
            company_name TEXT,
            industry TEXT,
            open NUMERIC,
            high NUMERIC,
            low NUMERIC,
            last_price NUMERIC,
            previous_close NUMERIC,
            change NUMERIC,
            percent_change NUMERIC,
            total_traded_volume BIGINT,
            total_traded_value NUMERIC,
            week_52_high NUMERIC,
            week_52_low NUMERIC,
            near_52w_high_percent NUMERIC,
            near_52w_low_percent NUMERIC,
            isin TEXT,
            fo_stock BOOLEAN,
            trade_date DATE,
            PRIMARY KEY (symbol, trade_date));